export default [
  {
    school: 'Gryffondor',
    coverImg: 'https://www.piwwie.com/wp-content/uploads/2020/04/gryff.jpg',
    HeadColor: '#f73f2a',
    textColor: '#f7e1df',
    presentation: '<p>Né aux alentours du 10ème siècle, Godric Gryffondor a fondé la maison éponyme lors de la création du Château afin d’accueillir chez lui n’importe quel élève avec un don magique. En effet, comme vous le savez peut-être, il a été un fervent partisan de la lutte contre la discrimination envers les Moldus de son vivant.</p><p>Il fut le premier possesseur du Choixpeau magique et de l’épée dite « de Gryffondor ». D’ailleurs, sachez qu’il était le duelliste le plus accompli de son époque. Y compris lorsqu’il s’agissait de se battre à l’épée, comme un simple moldu</p><p>Godric Gryffondor est né dans un village qui - par hommage - porte désormais son nom : Godric Hollow</p>',
    avantages: [
      "Globalement les enseignants vous aiment bien (à l'exception de l'un d'eux, mais on y reviendra plus tard.) Ils ne sont donc ni trop sévères ni injustes avec vous et ceux de votre Maison. Cela vous garanti donc une scolarité assez sereine. Qui plus est, l'ancien directeur de Poudlard et la directrice qui lui a succédé étant étant d'anciens Gryffondor, il se pourrait qu'il y ait un poil de favoritisme envers votre Maison lors du décompte final des points. Demandez donc aux Serpentard ce qu'il s'est passé en 1991 lors du décompte final. Je crois qu'ils l'ont encore en travers de la gorge...",
      "Globalement, les autres élèves vous respectent et vous apprécient vu qu'il n'y a pas de conflit entre votre Maison et celles de Serdaigle et Poufsouffle. Pour Serpentard, en revanche c'est une autre histoire... Cela vous assure donc là encore une scolarité sereine. (Exception faite lorsqu'un Tournoi des Trois Champions est organisé et que par un malheureux hasard un élève de votre Maison se trouve a y participer alors qu'il n'a pas l'âge requis. Dans ce cas, étrangement, les autres Maisons ne prendront pas parti pour la vôtre...) Mais bon, rassurez vous le Tournoi des Trois Sorciers reste exceptionnel, avec un peu de chance votre scolarité ne sera pas perturbnée par le prochain...",
      "Vous avez la chance d'avoir l'un des dortoirs les plus confortables. Feu de cheminées, fauteuils moelleux, ambiance feutrée, lit à baldaquins, en plus vous voilà relativement isolé du reste du château... Le dortoir Gryffondor est donc réputé être l'un des plus chaleureux. En concurrence avec celui des Poufsouffle, mais vous au moins ne risquez pas une douche au vinaigre si vous vous trompez de mot de passe ! Et puis grâce aux différents panneaux d'affichages vous ne louperez jamais un entrainement de Quidditch ni une bonne affaire.",
      "Si vous vous en montrez digne, vous pourrez avoir l'insigne honneur de voir - et même d'utiliser - l'épée de Gryffondor. une des reliques les plus célèbres de Poudlard. Peu d'élèves peuvent ainsi se vanter d'avoir utilisé cette relique et si les plus grands sorciers de tous les temps ont rêvé de cet honneur ils n'ont pas forcément pu concrétiser leur rêve. Si c'est pas la classe de pouvoir utiliser une telle arme pour détruire horcruxe et devenir un héros aux yeux du monde sorcier, je ne sais pas ce qu'il vous faut. Et si vous vous demandez ce que ça fait d'utiliser cette arme, demandez donc à Harry, Ron ou Neville !"
    ],
    inconvenients: [
      "Le directeur de la maison Serpentard (quel qu'il soit) aura tendance à vous détester. Aussi dites adieu à vos rêves de notes optimales dans la matière qu'il enseigne. Et si jamais vous êtes irréprochable au point qu'il ne puisse pas vous pénaliser sans faire preuve d'une mauvaise foi, attendez-vous à être traité de Miss-je-sais-tout ou autre joyeuseté de sa part. Forcément, ça risque de compliquer un poil votre scolarité dans cette matière. Surtout qu'il ne se gênera pas pour vous ôter honteusement des points et favoriser sa Maison en retour",
      "Votre dortoir est au septième étage. SEPTIÈME étage ! 7ème étage !!! En plus d’un nombre incalculable de marches à monter et descendre à longueur de journée (et je ne parle pas des allers-retours quand vous oubliez du matériel pour les cours), c’est autant de risques de vous faire embarquer par un escalier dans une direction qui n’est pas du tout celle que vous voulez… Pour le coup, si vous n’êtes pas sportifs, il va falloir le devenir vite. Ou être suffisamment organisé pour ne pas avoir à retourner au dortoir entre chaque cours. Et si ce n’est pas le cas, à vous les punitions à gogo pour vos retards en cours. Ou les retenues pour absence de matériel. Et oui, pas toujours simple de vouloir côtoyer les nuages !",
      "On attend de vous que vous soyez fort, hardi et brave (entre autre). Alors il va falloir aller puiser tout au fond de vous, dans des ressources que vous ignorez exister, pour trouver votre place dans cette Maison. Ça ne sera pas forcément facile, ni de tout repos pour vos nerfs. D’autant qu’il ne sera pas question d’appeler à l’aide si une araignée se tisse tranquillement une toile dans le coin de votre baldaquin. Le courage, ça commence déjà par affronter soit même ses peurs. Demandez donc à Ron Weasley si vous ne me croyez pas !",
      "Soyons honnête, si vous êtes à Gryffondor c’est que vous avez un comportement fonceur et bravache. Et ça ne va pas toujours vous servir croyez-moi. Impossible pour vous de rester de marbre devant un défi ou une action héroïque à tenter. Pas toujours facile dans ce genre de cas de concilier instinct de survie et besoin de frimer… Du coup vous risquez de vous trouver plus souvent qu’à votre tour face à des dangers auxquels vous ne pensiez pas vous voir exposé un jour. Que cela concerne pour une visite nocturne en forêt interdite ou un combat à mort face à un mage noir."
    ]
  },
  {
    school: 'Serpentard',
    coverImg: 'https://www.piwwie.com/wp-content/uploads/2020/04/serpentard.jpg',
    HeadColor: '#ccf74a',
    textColor: '#f1f7df',
    presentation: "<p>La Maison Serpentard a été édifiée par Salazar Serpentard, l’un des quatre fondateurs de Poudlard. Malin et roublard, Salazar Serpentard était souvent opposés aux autres fondateurs, surtout à propos de la façon de recruter les élèves. Pour lui, seuls les enfants d’une lignée de Sang-Pur devaient être en droit d’apprendre la Magie afin de renforcer les vielles familles et de préserver la pureté du sang de sorcier. À ce titre, et selon ses pensées, les enfants nés-moldus n’étaient pas dignes de recevoir cet enseignement. Selon la légende, lorsque la discorde devint trop importante entre les fondateurs, Salazar quitta Poudlard non sans avoir construit au coeur même du château une chambre secrète, la Chambre des Secrets. Seul son héritier pourrait ouvrir cette chambre afin de faire sortir le monstre y vivant. Ce monstre, aurait alors pour mission de chasser les enfants indignes – selon la pensée de Salazar – de l’École.</p><p>Sorcier de sang pur, Salazar était également connu pour sa capacité à parler le Fourchelang, le langage des serpents. Il savait aussi invoquer le sort de Legilimens. Ce dernier lui permettait de pénétrer dans l’esprit d’une personne et d’observer et d’influencer ses pensées et ses émotions. Serpentard était également dépositaire d‘une vielle et précieuse relique, un médaillon familial qui ne le quittait jamais.</p>",
    avantages: [
        "Une très grande majorité des élèves de Serpentard sont des enfants de vieilles et grandes lignées de Sang-pur. Les autres élèves de Poudlard en ont bien conscience et ont donc tendance à vous respecter – exception faite pour les Gryffondor. Il en sera de même pour les enseignants qui savent que leur carrière peut dépendre d’un seul mot de vos parents au Ministre de la Magie. Autant dire que vous serez relativement tranquille de ce côté. Et même si certains seront intraitables – pas vrai professeur McGonagall ? – d’autres seront facilement manipulables.",
        "Là où les Serdaigle sont unis de façade mais en compétition même entre eux, là où les Gryffondor s’occupent surtout de leurs amis, les Serpentard sont unis comme les doigts de la main. Un peu comme les Poufsouffle. De ce fait, en tant qu’élève de Serpentard, vous bénéficiez de la protection totale de votre Maison en cas de problème. Plus de raisons de craindre les fantômes, plus de raison de craindre les autres élèves dans les couloirs. Ni même de s’inquiéter pour vos devoirs. Si la Maison Serpentard gagne, c’est grâce à tout le monde, si elle échoue c’est de la faute de tous. Vous êtes unis dans la victoire comme dans la défaite !",
        "Si votre salle commune n’est pas la plus chaleureuse ou la plus haute, elle n’en est pas moins la plus luxueuse et en même temps la plus mystérieuse. Regardez toutes des pièces raffinées, ces tableaux médiévaux, ces lourdes lanternes. Ne dirait-on pas une épave gisant au fond des océans ? D’autant que la luminosité venant du Lac Noir y est pour beaucoup. En outre, elle est facile d’accès – bien plus que si vous aviez à grimper une tour – et toujours fraîche une fois de plus grâce à la présence du Lac Noir. Les anciens de votre Maison ont de plus toujours laissés entendre que la nuit, le clapotis des eaux du Lac contre les vitres s’avère très relaxant. Un son que les autres ne peuvent entendre.",
        "Je vais vous dire un secret. Un secret de Serpentard. Serpentard est la plus provocatrice des Maisons et le fait d’être perçu par les autres comme des provocateurs et des roublards présente quelques avantages, parfois très drôles ! Nombreux sont les Serpentard qui s’amusent à faire croire qu’ils manipulent de puissants sortilèges. Imitez-les et vous aurez la garantie d’être tranquille pour toute l’année scolaire. Et contrairement à ce que les autres élèves aiment à faire croire, ce n’est pas parce que vous avez mauvais fond que vous faites ça, mais bien pour la course à la victoire. Et dans cette course, tous les coups sont permis. Ce que les membres de votre Maison ont bien compris."
    ],
    inconvenients: [
        "Ne le cachons pas, la Maison Serpentard a mauvaise réputation. Nombreux Mages Noirs sont passé par les mêmes bancs que vous et elle ne s’en cache pas (à l’inverse des Gryffondor et Serdaigle qui le nient farouchement). Cette réputation trouve aussi son origine dans sa tradition de n’accepter que les élèves issus des plus grandes lignées. Et même si aujourd’hui à Serpentard beaucoup d’élèves ont un parent moldu, cette mauvaise image vous colle à la peau. Il faut dire que vos coups tordus et vos petits tours n’aident pas. Il va falloir vous y faire et accepter cette réputation, sinon votre année risque d’être compliquée.",
        "Si dans l’ensemble on respecte votre Maison ce n’est pas sans un soupçon de peur. Comme dit plus tôt, vos parents – et vous-même plus tard – peuvent faire ou défaire une carrière d’un claquement de doigts. Du coup, ne comptez pas trop sur les autres pour devenir vos amis. Ils vous craigneront plus qu’autre chose. En outre, cette technique ne marchera pas avec les Gryffondor, qui seront en opposition avec vous. Il en sera de même avec les Serdaigle, en constante compétition pour la première place, comme vous. Autant dire que vous serez seul en dehors de votre Maison, et qu’il va vous falloir un moral d’acier pour faire le poids face aux autres.",
        "Pas d’énigme ou de tapotage en rythme pour entrer dans votre salle commune mais un mot de passe. Un mot de passe qui change tous les 15 jours. Il va vous falloir une sacrée mémoire pour ne pas vous louper. Sinon, vous voilà à la porte jusqu’à ce qu’un autre élève de votre Maison ne vienne vous faire entrer. Autant dire que si vous avez laissés vos affaires dans votre chambre, vous risquez fortement d’arriver en retard en cours. Gare à la retenue ou les points en moins qui vont en découler. Un petit conseil : le tableau d’information est votre meilleur ami. N’oubliez pas de consulter régulièrement sa mise à jour ! Sinon, tant pis pour vous !",
        "L’honneur et les traditions des Serpentard sont des valeurs qui vous tiennent à cœur. Aussi, en appartenant à Serpentard, vous devrez toujours être au sommet pour mener votre Maison à la victoire. Pas de relâchement, ni le droit à la faute. N’oubliez pas, à Serpentard, quand vous jouez c’est uniquement pour gagner. Et il peut parfois s’agir d’un poids très lourd à porter ! Un poids doublé pour certains des héritiers des plus grandes lignées qui portent aussi ce fardeau pour perpétrer la grandeur de leur famille. J’espère que vous avez les épaules solides ! Et si vous pensez que qu’il s’agit d’un fardeau facile à porter, parlez en à Drago !"
    ]

  },
  {
    school: 'Poufsouffle',
    coverImg: 'https://www.piwwie.com/wp-content/uploads/2020/04/poufsouffle.jpg',
    HeadColor: '#f7c040',
    textColor: '#f7ece1',
    presentation: "<p>La création de cette maison revient à <b>Helga Poufsouffle</b>, lors de la fondation de Poudlard. Cette dernière fait figure de <b>modèle maternel</b> encore aujourd’hui. À l’époque, elle rassembla des gens aux modes de vie différents pour aider à construire Poudlard et était aimée pour ses manières charmantes. En outre, Helga Poufsouffle était particulièrement connue pour <b>ses sortilèges appliqués à la nourriture</b>. D’ailleurs, un bon nombre de recettes encore utilisées traditionnellement pour les fêtes de Poudlard proviennent d’elle. Elle a valorisé le <b>sens du partage et la bienveillance</b> et a donc souhaité que tous les élèves de sa Maison partage ces qualités. Par ailleurs, il s’agissait d’une grande amie de Rowena Serdaigle. Elle était originaire des vallée galloises et vécu, comme les trois autres fondateurs, au 10ème siècle.</p><p>Elle était propriétaire d’une coupe en or, finement ouvragée qui s’est transmise de génération en génération dans sa famille jusqu’à Hepzibah Smith. Malheureusement celle-ci a été assassinée par Tom Jesudor qui a volé la coupe pour en faire un <b>Horcruxe</b>.</p>",
    avantages: [
      'Vous aurez l’un des dortoir les plus confortable. À égalité avec Gryffondor mais vous au moins vous n’avez pas sept étages à monter pour rejoindre votre chambre. C’est bien plus facile quand on est tête en l’air et qu’on oublie régulièrement ses affaires ! De plus, sa localisation vous permet des petites excursions en cuisine en cas de fringales. Et pour finir, la position en sous-sol desdits dortoirs vous assure un sommeil parfait, abrité des orages et du vent. Un luxe auquel ceux qui dorment en haut des tours ne peuvent pas prétendre.',
      'Dans l’absolu, tout le monde vous apprécie et personne ne trouve quoique ce soit à redire aux membres de votre Maison. De l’avis général, vous êtes sans doute les élèves les plus aimables et agréables de Poudlard. Et vous faites de ce fait partie de la Maison la plus sympathique, la plus honnête et la plus persévérante du Château. Les professeurs n’ont pas de préjugés contre vous, ce qui assurera une scolarité plutôt calme et tranquille. Vous pourrez donc faire votre petit bout de chemin sans vous inquiéter des coups-bas et de la concurrence au sein même de votre Maison comme cela peut arriver chez d’autres.',
      'Contrairement à ce qui se dit et à ce que l’ensemble des autres Maison croit, Poufsouffle a aussi quelques sorciers et sorcières célèbres dans son histoire.  Grogan Stump, fut l’un des ministres de la Magie les plus populaires de tous les temps. Tout comme l’étaient Artemisia Lufkin qui mit en place la Coupe du Monde de Quidditch et Dugald McPhail, qui inventa le Magicobus, tous deux également très doués et respectés. Il existe donc bien de nombreux sorciers célèbres au sein de votre Maison. Vous n’avez donc pas à rougir de votre héritage magique. D’ailleurs, Poufsouffle est la seule Maison a ne pas avoir formé de Mage Noir, à l’inverse des trois autres !',
      'Les Poufsouffle sont farouchement loyaux. Aussi gare à ceux osant s’en prendre à un membre de votre Maison. Si votre emblème, le Blaireau peut parfois prêter à rire ou être l’objet de médisances, nombreux sont ceux qui oublient de quoi il est capable pour son territoire ou ses proches. À l’instar de cet animal, votre Maison entière est prête à faire front si quelqu’un s’en prend à un de ses membres. Appartenir à Poufsouffle, c’est donc avoir la certitude qu’il y aura toujours quelqu’un pour vous aider et vous défendre en cas de problème. Un avantage non négligeable si vous n’avez pas l’esprit à la bagarre mais plus à l’études des créatures et des plantes.'
    ],
    inconvenients: [
      'L’inconvénient sans doute majeur à appartenir à la Maison Poufsouffle, c’est le risque de finir parfumé au vinaigre si vous vous trompez dans le mot de passe. Et cela peut arriver très vite. Un livre de cours oublié, un retour précipité au dortoir, un mot de passe donné trop vite ou sur le mauvais tonneau et hop. Un bain de vinaigre. Du coup, il ne vous reste plus qu’à prendre une bonne douche et changer de vêtements avant de retourner en cours. Ce qui risque de vous mettre bien en retard. Autant dire qu’à chaque fois que vous devrez rentrer dans votre dortoir, il vous faudra faire preuve de prudence pour ne pas vous louper.',
      'Les Poufsouffle ne sont pas vantard, loin de là. De ce fait, lorsque vous réalisez un exploit, à l’inverse des autres Maisons, vous n’en faites pas toute une histoire. Du coup, vos exploits restent en grande partie ignorés et vous restez aux yeux des autres Maison, une Maison faible et sans grandeur. Une réputation qu’il peut être parfois difficile à porter. Tout le monde ne supporte pas d’être constamment rabaissé ou que l’on remette en doute vos capacités. Aussi, il vous faudra avoir des nerfs d’acier et une confiance en vous inébranlable pour ne pas laisser les ragots et autres médisances vous attendre. Sinon vos sept années au sein de Poudlard risquent d’être longues et compliquées.',
      'Si l’on parle beaucoup au sein de l’école de la rivalité Gryffondor/Serpentard, on parle beaucoup moins de celle Poufsouffle/Serdaigle. Néanmoins elle existe aussi. Ces derniers ont tendance à vous trouver peu intelligents et jugent donc que vous ne pouvez pas avoir de grands sorciers issus de vos rangs. Ce qui, vous le savez, est évidement faux. Il n’empêche que dans ces conditions, il vous sera difficile de vous faire respecter par les Serdaigle et difficile de vous faire une place dans l’école. Heureusement pour vous, l’essentiel des Poufsouffle est au-dessus de ce genre de considérations. Mais si ce n’est pas votre cas, il va falloir apprendre à faire avec, à serrer des dents et à plier l’échine.',
      'Votre sens de la justice vous pousse à toujours prendre la défense du coté des justes. Et si vous n’avez pas une âme de combattant ou une âme de bagarreur cela risque de compliquer un peu les choses. Après, il faut tout de même admettre qu’il est rare que se jouent des batailles concernant l’avenir du monde. Mais dans ces cas là, à l’inverse des autres Maisons (seuls les plus âgés des Gryffondor et certains des Serdaigle ont participé à la Bataille contre Vous-savez-qui et ne parlons pas des Serpentard), la votre fait front et tout le monde se retrouve à combattre. Néanmoins, vous ne devrez pas avoir trop souvent ce genre de problème majeur. Il n’empêche que c’est plus fort que vous. Si un combat vous semble injuste ou déloyal, vous allez forcément vous en mêler.'
    ]
  },
  {
    school: 'Serdaigle',
    coverImg: 'https://www.piwwie.com/wp-content/uploads/2020/04/serdaigle.jpg',
    HeadColor: '#4fbaf7',
    textColor: '#dfeef7',
    presentation: '<p>Née elle aussi aux alentours du 10ème siècle, dans les montagnes d’Ecosse, Rowena Serdaigle fut l’un des quatre fondateurs de Poudlard. D’ailleurs, le concept du château changeant tout le temps de disposition lui est attribué. Il est probable que ce soit elle aussi qui proposa la création de pièces changeantes comme la célèbre (et secrète) Salle sur Demande. Elle est surtout reconnue pour son intelligence et sa créativité. Elle a donc créé la maison qui porte son nom et défend ces valeurs.</p><p>Selon la légende, Rowena était la plus brillante sorcière de son époque. Toujours selon la légende, elle eut le cœur brisé – pour une raison inconnue – ce qui contribua néanmoins à sa disparition précoce. Certains pensent cependant que ce drame est lié à la disparition de son diadème magique. Ce dernier prodiguait la sagesse à quiconque le portait et a été volé par sa propre fille, Hélena</p>',
    avantages: [
      'Votre dortoir est l’un des plus calme et adapté à l’étude. Ici personne ne haussera le ton et tout le monde respectera votre besoin de silence pour travailler ou réfléchir. Le plafond peint sera propice à vos révisions sur l’astronomie. Et puis après tout, qui ne rêve pas de dormir sous un ciel étoilé sans les inconvénients d’une nuit à la belle étoile ? Et pour beaucoup, le bruit du vent sifflant autour des fenêtres s’avère très relaxant. En outre, aucune autre maison ne dispose d’une vue aussi exceptionnelle que celle de votre tour. Si avec ça votre imagination et votre esprit créatif ne sont pas  stimulés je ne peux plus rien pour vous.',
      'Avec votre réputation de personne sage, intelligente et réfléchi, on viendra vous consulter en cas de difficultés ou pour des conseils. Libre à vous ensuite de répondre ou non aux questions que l’on vous pose, de monnayer votre savoir ou tout simplement d’ignorer les demandes que vous recevrez. Mais il n’en reste pas moins que vous et les membres de votre maison avez la réputation d’avoir réponse à tout. Et il faut admettre que cela peut de temps en temps flatter l’ego que de voir les autres maisons venir vous demander de l’aide.',
      'À Serdaigle, l’originalité et la créativité sont de mise. De ce fait, on y trouve facilement des excentriques et des originaux et ces derniers sont respectés par tous les membres de la Maison bleue et bronze. En effet, les Serdaigle estiment avoir le droit de porter ce qui leur plaît, de penser comme bon leur semble et de dire ce qu’ils pensent. Les gens différents ne les impressionnent pas, au contraire, même ils savent les apprécier à leur juste valeur. De ce fait, dans cette maison vous pourrez laisser libre court à votre originalité sans craindre les quolibets et autres moqueries. À vous les garde-robes les plus loufoques les unes que les autres, les bijoux fait mains ou les accessoires divers !',
      'De manière générale, Serdaigle a formé nombre de grands et célèbres sorciers. Ainsi, votre maison peut se vanter d’avoir une histoire et un passé illustre. En effet, une grande majorité des plus grands inventeurs et pionniers du monde magique ont étudié à Serdaigle. Comme Perpetua Fancourt, qui a inventé le Lunascope, Laverne de Montmorency, l’inventeur de nombreux philtres d’amour ou Ignatia Wildsmith, l’inventrice de la Poudre de Cheminette. On trouve aussi de nombreux anciens ministres de la Magie dans les rangs des Serdaigle. Bref, appartenir à cette maison c’est l’assurance d’avoir de bonnes références.'
    ],
    inconvenients: [
      'Si au sein de votre Maison l’originalité et la créativité sont de mise, les personnes trop originales et excentriques risquent de souffrir du regard des autres. À l’image d’Ulric le Follingue et son célèbre chapeau méduse, moqué par nombre de sorciers. Ou de Luna Lovegood affublée du surnom de Loufoca en raison de son style vestimentaire particulier et de son air toujours un peu rêveur. Autant dire que si vous ne supportez pas les moqueries et autres quolibets, il va vous falloir laisser votre créativité de côté pour rentrer dans le moule…',
      'Certes, le heurtoir magique permet de filtrer les entrées dans la salle commune plus efficacement qu’un simple mot de passe, mais vous pouvez vous retrouver à la porte si vous êtes en manque d’imagination. De ce fait, il faut reconnaître qu’il n’est pas rare de trouver une vingtaine d’élèves regroupés devant la porte, tentant de trouver la solution à l’énigme posée. Alors cela peut s’avérer la parfaite occasion pour en apprendre plus ou rencontrer les autres années, mais cela vous complique grandement les choses quand il vous faut rentrer en vitesse dans le dortoir pour récupérer un livre ou un chaudron oublié pour votre cours imminent…',
      'La curiosité des Serdaigle est proverbiale. Si vous avez rejoins cette maison nul doute que vous avez en vous beaucoup de curiosité également. Gare cependant à ne pas vous laisser déborder par celle-ci, que ce soit en multipliant les études comme celles portant sur la lévitation ou l’utilisation magique des crottes de nez de trolls ou encore l’ovomancie. Cela peut être certes intéressant, mais passer des nuits entières à casser des œufs sur un coin de table en observant le côté sur lequel tombe le jaune pour en tirer des prédictions peut nuire à votre scolarité.',
      'On parle souvent de l’intérêt des Serdaigle pour les études. On parle plus rarement de leur course pour être les meilleurs en tout. Et cela ne concerne pas que la Maison Serdaigle face aux autres Maisons de manière générale mais bien les élèves entre eux également. Alors certes, vous trouverez toujours un compagnon de Maison pour vous aider à faire des recherches sur une discipline obscure qui vous passionne tant. Mais vous trouverez aussi de féroces adversaires qui se livrent, au sein même de leur Maison, une guerre sans merci pour obtenir les meilleures notes.  Et être le premier de sa classe et de sa Maison ! Si vous ne supportez pas la pression, cela risque donc de compliquer quelque peu votre scolarité.'
    ]

  }
]